Distributions defined in the `~plasmapy.distribution` module will now raise a ``ValueError`` for an improper ``units`` parameter.
